/**
 * Ensure .rclaude/ directory exists in the given CWD with a .gitignore.
 * Returns the absolute path to the directory.
 */

import { existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { ensureSecureDir } from '../shared/secure-temp'

/**
 * Nothing under `.rclaude/` belongs in the host project's git. It is runtime
 * state: secrets, stream logs, and a board that rewrites hundreds of files a
 * day.
 *
 * This file previously carried `!project/` under a comment reading "Keep the
 * project board and config committed". Those negations never took effect --
 * a parent .gitignore excluding the `.rclaude/` DIRECTORY means git never
 * descends far enough to read this file at all. It was a written-down promise
 * with no mechanism behind it, and it is what convinced a later change that
 * committing the board was the intended design. Do not reintroduce it.
 */
const RCLAUDE_GITIGNORE = `# Auto-generated by rclaude.
# Runtime state only -- none of this belongs in your repository.
*
`

/**
 * Every ignore file rclaude has previously shipped, byte for byte.
 *
 * Both of them state -- in words a human reads and believes -- that the board
 * is committed, and neither ever committed anything. Correcting the generator
 * only reaches projects created afterwards; every project that already exists
 * keeps its copy of the claim on disk forever, because the write below is
 * create-only. So we replace our own past output when we recognise it exactly.
 *
 * The match is exact on purpose. One byte of difference means a human edited
 * the file, and a hand-edited file is never touched -- see the `existsSync`
 * ladder in `writeRclaudeGitignore`. Adding a new generation here without
 * appending the one it replaces would strand that generation permanently.
 */
const SUPERSEDED_GITIGNORES: readonly string[] = [
  // Shipped until 2026-08-21. `!project/` under a parent that excludes the
  // `.rclaude/` DIRECTORY is unreachable; git never reads this file.
  '# Auto-generated by rclaude\n# Session temp files\nsettings/\n\n# Keep project board and config committed\n!project/\n!rclaude.json\n',
  // `4f7761ba`, live for ~90 minutes on 2026-08-21. Anchored the negations so
  // they would survive `/*`, which fixed the wrong half: the parent exclusion
  // is what stops git, and `7ee496a4` reversed the whole direction anyway.
  '# Auto-generated by rclaude.\n#\n# project/ is the board. It is the only durable copy of itself, so it belongs in\n# git. Everything else in here is session temp files, secrets and stream logs.\n#\n# This file only has an effect if no parent .gitignore excludes the .rclaude/\n# DIRECTORY -- git never descends into an excluded directory. Upstream must say\n# `.rclaude/*` (the contents), not `.rclaude/`.\n/*\n!/project/\n!/rclaude.json\n',
]

export function ensureRclaudeDir(cwd: string): string {
  const dir = join(cwd, '.rclaude')

  // Migrate tasks/ -> project/ if old name exists
  const oldTasks = join(dir, 'tasks')
  const newProject = join(dir, 'project')
  if (existsSync(oldTasks) && !existsSync(newProject)) {
    renameSync(oldTasks, newProject)
  }

  // `settings/` holds secrets + transcript content (MCP configs, merged
  // settings, system prompts, headless stream logs) -- owner-only (0700).
  // `project/` is the board; it is read by tooling, so group/world-readable.
  ensureSecureDir(join(dir, 'settings'))
  mkdirSync(join(dir, 'project'), { recursive: true })

  writeRclaudeGitignore(dir)
  return dir
}

/**
 * Create the ignore file, or replace a superseded generation of our own.
 *
 * Four cases, in the order the ladder tests them:
 *
 * - absent          -> write the current bytes
 * - present, ours, superseded -> replace (the migration this function exists for)
 * - present, unreadable       -> leave it. A directory or a mode-000 file here
 *   is somebody's deliberate doing, and writing anyway would throw on a path
 *   that runs during every host boot.
 * - present, anything else    -> leave it. Hand-edited, or already current.
 */
function writeRclaudeGitignore(dir: string): void {
  const path = join(dir, '.gitignore')
  if (existsSync(path)) {
    const current = readIfReadable(path)
    if (current === null || !SUPERSEDED_GITIGNORES.includes(current)) return
  }
  writeFileSync(path, RCLAUDE_GITIGNORE)
}

function readIfReadable(path: string): string | null {
  try {
    return readFileSync(path, 'utf8')
  } catch {
    return null
  }
}
