/**
 * Ensure .rclaude/ directory exists in the given CWD with a .gitignore.
 * Returns the absolute path to the directory.
 */

import { existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { ensureSecureDir } from '../shared/secure-temp'

/**
 * The rule that was shipped until 2026-08-21, and that never once took effect.
 *
 * `settings/` + `!project/` reads like intent, but a bare `!project/` cannot
 * re-include anything while a PARENT .gitignore excludes the `.rclaude/`
 * DIRECTORY -- git does not descend into an excluded directory, so this file
 * was never even read. It was a written-down promise with no mechanism behind
 * it, which is worse than no promise at all.
 *
 * Kept verbatim so the exact-match migration below can recognise it. Anything a
 * user has since edited by hand is left alone.
 */
const STALE_GITIGNORE =
  '# Auto-generated by rclaude\n# Session temp files\nsettings/\n\n# Keep project board and config committed\n!project/\n!rclaude.json\n'

/**
 * Self-contained and anchored. `/*` matches only the DIRECT children of
 * `.rclaude/`, so the negations survive and files nested under `project/` are
 * never re-matched. An unanchored `*` would match every basename at any depth
 * and quietly re-ignore the whole board.
 *
 * This still needs the parent .gitignore to exclude `.rclaude/*` (contents)
 * rather than `.rclaude/` (the directory) -- hence the note in the file.
 */
const BOARD_GITIGNORE = `# Auto-generated by rclaude.
#
# project/ is the board. It is the only durable copy of itself, so it belongs in
# git. Everything else in here is session temp files, secrets and stream logs.
#
# This file only has an effect if no parent .gitignore excludes the .rclaude/
# DIRECTORY -- git never descends into an excluded directory. Upstream must say
# \`.rclaude/*\` (the contents), not \`.rclaude/\`.
/*
!/project/
!/rclaude.json
`

export function ensureRclaudeDir(cwd: string): string {
  const dir = join(cwd, '.rclaude')

  // Migrate tasks/ -> project/ if old name exists
  const oldTasks = join(dir, 'tasks')
  const newProject = join(dir, 'project')
  if (existsSync(oldTasks) && !existsSync(newProject)) {
    renameSync(oldTasks, newProject)
  }

  // `settings/` holds secrets + transcript content (MCP configs, merged
  // settings, system prompts, headless stream logs) -- owner-only (0700).
  // `project/` is the git-committed board, so it stays group/world-readable.
  ensureSecureDir(join(dir, 'settings'))
  mkdirSync(join(dir, 'project'), { recursive: true })

  writeBoardGitignore(dir)
  return dir
}

/** Write the board .gitignore, replacing the known-broken generation in place.
 *  A hand-edited file is never touched -- only the byte-for-byte stale one. */
function writeBoardGitignore(dir: string): void {
  const path = join(dir, '.gitignore')
  if (existsSync(path) && safeRead(path) !== STALE_GITIGNORE) return
  writeFileSync(path, BOARD_GITIGNORE)
}

function safeRead(path: string): string | null {
  try {
    return readFileSync(path, 'utf8')
  } catch {
    return null
  }
}
