/**
 * `ensureRclaudeDir` creates the runtime state directory a host writes into.
 *
 * Nothing under `.rclaude/` is tracked in git -- `7ee496a4` settled that, and
 * `72a8d449` made the generator emit a bare `*`. The previous version of this
 * file asserted the opposite (an anchored .gitignore with `!/project/`
 * negations) and sat RED on main for hours after the reversal; it was deleted
 * wholesale in `6f8f7dc2`, together with a lint gate -- `lint:no-config-tests`
 * -- that now refuses any test asserting version-control configuration.
 *
 * That gate once made the ignore-file contract unwriteable here -- its token
 * ban matched the filename itself, and a bytes assertion needs the filename to
 * find the file. `lint-no-config-tests-bans-the-bytes-test` split the ban into
 * two classes, so the permitted shape is now expressible and is exercised
 * below: our code writes into a tmpdir, and we read OUR OWN bytes back. No git
 * runs, and nothing here reads the copy checked into this repo -- which is the
 * line the gate draws, and the reason these two tests pass it.
 *
 * `board-not-actually-in-git` then found that fixing the generator was only half
 * the job: the write is create-only, so every project made before `72a8d449`
 * still holds a file saying `!project/` -- the sentence a later card read as
 * proof the board was version-controlled. Four tests below pin the migration
 * that replaces our own superseded output, and the exactness that keeps it away
 * from anything a human touched.
 *
 * The rest is the directory work, which is ours and is untested otherwise: the
 * layout it creates, the owner-only mode on `settings/`, and the `tasks/` ->
 * `project/` rename it carries for pre-rename projects.
 */

import { describe, expect, it } from 'bun:test'
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { ensureRclaudeDir } from './ensure-rclaude-dir'

function scratch(): string {
  return mkdtempSync(join(tmpdir(), 'ensure-rclaude-'))
}

/**
 * The exact bytes `ensureRclaudeDir` is contracted to emit, written out here
 * rather than imported from the module under test. Importing the constant
 * would make this assertion tautological: the test would agree with whatever
 * the source happened to say, including a change that un-ignores the tree.
 *
 * A bare `*` is the whole policy. `72a8d449` settled it after an anchored
 * variant carrying `!project/` negations was found never to have fired once --
 * a parent ignore rule excluding the `.rclaude/` DIRECTORY means git never
 * descends far enough to read this file. If a future edit reintroduces a
 * negation, this test is what says so.
 */
const EXPECTED_BYTES =
  '# Auto-generated by rclaude.\n# Runtime state only -- none of this belongs in your repository.\n*\n'

/**
 * The two ignore files rclaude shipped before the bytes above, transcribed here
 * from `git show` rather than imported, for the same reason as `EXPECTED_BYTES`:
 * importing the module's own list would make these tests agree with any future
 * edit to it, including one that drops a generation and strands it.
 *
 * Both say the board is committed. Neither ever committed anything -- a
 * negation under a directory a parent ignore rule excludes is unreachable. A
 * project created before `72a8d449` still has one of these on disk, saying so,
 * which is what these tests exist to end.
 */
const SUPERSEDED_2026_08_21 =
  '# Auto-generated by rclaude\n# Session temp files\nsettings/\n\n# Keep project board and config committed\n!project/\n!rclaude.json\n'

const SUPERSEDED_ANCHORED =
  '# Auto-generated by rclaude.\n#\n# project/ is the board. It is the only durable copy of itself, so it belongs in\n# git. Everything else in here is session temp files, secrets and stream logs.\n#\n# This file only has an effect if no parent .gitignore excludes the .rclaude/\n# DIRECTORY -- git never descends into an excluded directory. Upstream must say\n# `.rclaude/*` (the contents), not `.rclaude/`.\n/*\n!/project/\n!/rclaude.json\n'

/** Seed `.rclaude/.gitignore` with `body` in a fresh scratch cwd. */
function seedIgnore(body: string): { cwd: string; dir: string } {
  const cwd = scratch()
  const dir = join(cwd, '.rclaude')
  mkdirSync(dir, { recursive: true })
  writeFileSync(join(dir, '.gitignore'), body)
  return { cwd, dir }
}

describe('ensureRclaudeDir', () => {
  it('creates settings/ owner-only and project/ readable, and returns the dir', () => {
    const cwd = scratch()
    const dir = ensureRclaudeDir(cwd)

    expect(dir).toBe(join(cwd, '.rclaude'))
    expect(existsSync(join(dir, 'settings'))).toBe(true)
    expect(existsSync(join(dir, 'project'))).toBe(true)
    // settings/ holds secrets and stream logs: no group or world bits at all.
    expect(statSync(join(dir, 'settings')).mode & 0o077).toBe(0)
    // project/ is the board; tooling reads it, so it stays readable.
    expect(statSync(join(dir, 'project')).mode & 0o400).toBe(0o400)

    rmSync(cwd, { recursive: true, force: true })
  })

  it('writes the ignore bytes it promises on a fresh directory', () => {
    const cwd = scratch()
    const dir = ensureRclaudeDir(cwd)

    // Our own output, read back out of a tmpdir our own call just populated.
    expect(readFileSync(join(dir, '.gitignore'), 'utf8')).toBe(EXPECTED_BYTES)

    rmSync(cwd, { recursive: true, force: true })
  })

  it('never clobbers a hand-edited ignore file', () => {
    const handEdited = '# I edited this on purpose\n*\n!my-notes.md\n'
    const { cwd, dir } = seedIgnore(handEdited)

    ensureRclaudeDir(cwd)

    // The behavioural contract on this function's file write: it creates, and
    // it replaces only bytes it recognises as its own. Widening that to an
    // unconditional write turns every host boot into silent data loss for
    // anyone who customised this file.
    expect(readFileSync(join(dir, '.gitignore'), 'utf8')).toBe(handEdited)

    rmSync(cwd, { recursive: true, force: true })
  })

  it('replaces the 2026-08-21 generation, which claimed the board was committed', () => {
    const { cwd, dir } = seedIgnore(SUPERSEDED_2026_08_21)

    ensureRclaudeDir(cwd)

    // Fixing the generator alone reaches new projects only. Every project made
    // before the fix keeps a file on disk asserting `!project/` -- the sentence
    // that convinced a later change the board was version-controlled.
    expect(readFileSync(join(dir, '.gitignore'), 'utf8')).toBe(EXPECTED_BYTES)

    rmSync(cwd, { recursive: true, force: true })
  })

  it('replaces the anchored generation too', () => {
    const { cwd, dir } = seedIgnore(SUPERSEDED_ANCHORED)

    // Live for about ninety minutes, so few projects carry it -- but leaving it
    // off the list would strand those few with the loudest version of the claim
    // (its own comment argues the board "belongs in git").
    ensureRclaudeDir(cwd)

    expect(readFileSync(join(dir, '.gitignore'), 'utf8')).toBe(EXPECTED_BYTES)

    rmSync(cwd, { recursive: true, force: true })
  })

  it('leaves a near-miss alone -- the match is exact, not fuzzy', () => {
    // One appended line. A prefix or header match would call this ours and
    // silently discard the user's edit; only byte equality distinguishes our
    // own past output from a file somebody adapted from it.
    const adapted = `${SUPERSEDED_2026_08_21}!notes/\n`
    const { cwd, dir } = seedIgnore(adapted)

    ensureRclaudeDir(cwd)

    expect(readFileSync(join(dir, '.gitignore'), 'utf8')).toBe(adapted)

    rmSync(cwd, { recursive: true, force: true })
  })

  it('leaves the current bytes in place rather than rewriting them each boot', () => {
    const { cwd, dir } = seedIgnore(EXPECTED_BYTES)
    const before = statSync(join(dir, '.gitignore')).mtimeMs

    ensureRclaudeDir(cwd)

    expect(readFileSync(join(dir, '.gitignore'), 'utf8')).toBe(EXPECTED_BYTES)
    expect(statSync(join(dir, '.gitignore')).mtimeMs).toBe(before)

    rmSync(cwd, { recursive: true, force: true })
  })

  it('migrates a pre-rename tasks/ directory to project/', () => {
    const cwd = scratch()
    mkdirSync(join(cwd, '.rclaude', 'tasks'), { recursive: true })
    writeFileSync(join(cwd, '.rclaude', 'tasks', 'card.md'), 'body\n')

    ensureRclaudeDir(cwd)

    expect(existsSync(join(cwd, '.rclaude', 'tasks'))).toBe(false)
    expect(readFileSync(join(cwd, '.rclaude', 'project', 'card.md'), 'utf8')).toBe('body\n')

    rmSync(cwd, { recursive: true, force: true })
  })

  it('never merges tasks/ into an existing project/', () => {
    const cwd = scratch()
    mkdirSync(join(cwd, '.rclaude', 'tasks'), { recursive: true })
    mkdirSync(join(cwd, '.rclaude', 'project'), { recursive: true })
    writeFileSync(join(cwd, '.rclaude', 'tasks', 'old.md'), 'old\n')
    writeFileSync(join(cwd, '.rclaude', 'project', 'new.md'), 'new\n')

    ensureRclaudeDir(cwd)

    // Both survive untouched: a rename here would silently bury one of them.
    expect(readFileSync(join(cwd, '.rclaude', 'tasks', 'old.md'), 'utf8')).toBe('old\n')
    expect(readFileSync(join(cwd, '.rclaude', 'project', 'new.md'), 'utf8')).toBe('new\n')

    rmSync(cwd, { recursive: true, force: true })
  })

  it('is idempotent and preserves what is already there', () => {
    const cwd = scratch()
    ensureRclaudeDir(cwd)
    writeFileSync(join(cwd, '.rclaude', 'project', 'card.md'), 'kept\n')

    expect(ensureRclaudeDir(cwd)).toBe(join(cwd, '.rclaude'))
    expect(readFileSync(join(cwd, '.rclaude', 'project', 'card.md'), 'utf8')).toBe('kept\n')

    rmSync(cwd, { recursive: true, force: true })
  })
})
