/**
 * Ensure .rclaude/ directory exists in the given CWD with a .gitignore.
 * Returns the absolute path to the directory.
 */

import { existsSync, mkdirSync, renameSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { ensureSecureDir } from '../shared/secure-temp'

/**
 * Nothing under `.rclaude/` belongs in the host project's git. It is runtime
 * state: secrets, stream logs, and a board that rewrites hundreds of files a
 * day.
 *
 * This file previously carried `!project/` under a comment reading "Keep the
 * project board and config committed". Those negations never took effect --
 * a parent .gitignore excluding the `.rclaude/` DIRECTORY means git never
 * descends far enough to read this file at all. It was a written-down promise
 * with no mechanism behind it, and it is what convinced a later change that
 * committing the board was the intended design. Do not reintroduce it.
 */
const RCLAUDE_GITIGNORE = `# Auto-generated by rclaude.
# Runtime state only -- none of this belongs in your repository.
*
`

export function ensureRclaudeDir(cwd: string): string {
  const dir = join(cwd, '.rclaude')

  // Migrate tasks/ -> project/ if old name exists
  const oldTasks = join(dir, 'tasks')
  const newProject = join(dir, 'project')
  if (existsSync(oldTasks) && !existsSync(newProject)) {
    renameSync(oldTasks, newProject)
  }

  // `settings/` holds secrets + transcript content (MCP configs, merged
  // settings, system prompts, headless stream logs) -- owner-only (0700).
  // `project/` is the board; it is read by tooling, so group/world-readable.
  ensureSecureDir(join(dir, 'settings'))
  mkdirSync(join(dir, 'project'), { recursive: true })

  const gitignorePath = join(dir, '.gitignore')
  if (!existsSync(gitignorePath)) {
    writeFileSync(gitignorePath, RCLAUDE_GITIGNORE)
  }
  return dir
}
