/**
 * `ensureRclaudeDir` creates the runtime state directory a host writes into.
 *
 * Nothing under `.rclaude/` is tracked in git -- `7ee496a4` settled that, and
 * `72a8d449` made the generator emit a bare `*`. The previous version of this
 * file asserted the opposite (an anchored .gitignore with `!/project/`
 * negations) and sat RED on main for hours after the reversal; it was deleted
 * wholesale in `6f8f7dc2`, together with a lint gate -- `lint:no-config-tests`
 * -- that now refuses any test asserting version-control configuration.
 *
 * That gate once made the ignore-file contract unwriteable here -- its token
 * ban matched the filename itself, and a bytes assertion needs the filename to
 * find the file. `lint-no-config-tests-bans-the-bytes-test` split the ban into
 * two classes, so the permitted shape is now expressible and is exercised
 * below: our code writes into a tmpdir, and we read OUR OWN bytes back. No git
 * runs, and nothing here reads the copy checked into this repo -- which is the
 * line the gate draws, and the reason these two tests pass it.
 *
 * The rest is the directory work, which is ours and is untested otherwise: the
 * layout it creates, the owner-only mode on `settings/`, and the `tasks/` ->
 * `project/` rename it carries for pre-rename projects.
 */

import { describe, expect, it } from 'bun:test'
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { ensureRclaudeDir } from './ensure-rclaude-dir'

function scratch(): string {
  return mkdtempSync(join(tmpdir(), 'ensure-rclaude-'))
}

/**
 * The exact bytes `ensureRclaudeDir` is contracted to emit, written out here
 * rather than imported from the module under test. Importing the constant
 * would make this assertion tautological: the test would agree with whatever
 * the source happened to say, including a change that un-ignores the tree.
 *
 * A bare `*` is the whole policy. `72a8d449` settled it after an anchored
 * variant carrying `!project/` negations was found never to have fired once --
 * a parent ignore rule excluding the `.rclaude/` DIRECTORY means git never
 * descends far enough to read this file. If a future edit reintroduces a
 * negation, this test is what says so.
 */
const EXPECTED_BYTES =
  '# Auto-generated by rclaude.\n# Runtime state only -- none of this belongs in your repository.\n*\n'

describe('ensureRclaudeDir', () => {
  it('creates settings/ owner-only and project/ readable, and returns the dir', () => {
    const cwd = scratch()
    const dir = ensureRclaudeDir(cwd)

    expect(dir).toBe(join(cwd, '.rclaude'))
    expect(existsSync(join(dir, 'settings'))).toBe(true)
    expect(existsSync(join(dir, 'project'))).toBe(true)
    // settings/ holds secrets and stream logs: no group or world bits at all.
    expect(statSync(join(dir, 'settings')).mode & 0o077).toBe(0)
    // project/ is the board; tooling reads it, so it stays readable.
    expect(statSync(join(dir, 'project')).mode & 0o400).toBe(0o400)

    rmSync(cwd, { recursive: true, force: true })
  })

  it('writes the ignore bytes it promises on a fresh directory', () => {
    const cwd = scratch()
    const dir = ensureRclaudeDir(cwd)

    // Our own output, read back out of a tmpdir our own call just populated.
    expect(readFileSync(join(dir, '.gitignore'), 'utf8')).toBe(EXPECTED_BYTES)

    rmSync(cwd, { recursive: true, force: true })
  })

  it('never clobbers a hand-edited ignore file', () => {
    const cwd = scratch()
    const dir = join(cwd, '.rclaude')
    mkdirSync(dir, { recursive: true })
    const handEdited = '# I edited this on purpose\n*\n!my-notes.md\n'
    writeFileSync(join(dir, '.gitignore'), handEdited)

    ensureRclaudeDir(cwd)

    // The one behavioural contract on this function's single file write: it
    // creates, it never overwrites. Dropping the existsSync guard turns every
    // host boot into silent data loss for anyone who customised this file.
    expect(readFileSync(join(dir, '.gitignore'), 'utf8')).toBe(handEdited)

    rmSync(cwd, { recursive: true, force: true })
  })

  it('migrates a pre-rename tasks/ directory to project/', () => {
    const cwd = scratch()
    mkdirSync(join(cwd, '.rclaude', 'tasks'), { recursive: true })
    writeFileSync(join(cwd, '.rclaude', 'tasks', 'card.md'), 'body\n')

    ensureRclaudeDir(cwd)

    expect(existsSync(join(cwd, '.rclaude', 'tasks'))).toBe(false)
    expect(readFileSync(join(cwd, '.rclaude', 'project', 'card.md'), 'utf8')).toBe('body\n')

    rmSync(cwd, { recursive: true, force: true })
  })

  it('never merges tasks/ into an existing project/', () => {
    const cwd = scratch()
    mkdirSync(join(cwd, '.rclaude', 'tasks'), { recursive: true })
    mkdirSync(join(cwd, '.rclaude', 'project'), { recursive: true })
    writeFileSync(join(cwd, '.rclaude', 'tasks', 'old.md'), 'old\n')
    writeFileSync(join(cwd, '.rclaude', 'project', 'new.md'), 'new\n')

    ensureRclaudeDir(cwd)

    // Both survive untouched: a rename here would silently bury one of them.
    expect(readFileSync(join(cwd, '.rclaude', 'tasks', 'old.md'), 'utf8')).toBe('old\n')
    expect(readFileSync(join(cwd, '.rclaude', 'project', 'new.md'), 'utf8')).toBe('new\n')

    rmSync(cwd, { recursive: true, force: true })
  })

  it('is idempotent and preserves what is already there', () => {
    const cwd = scratch()
    ensureRclaudeDir(cwd)
    writeFileSync(join(cwd, '.rclaude', 'project', 'card.md'), 'kept\n')

    expect(ensureRclaudeDir(cwd)).toBe(join(cwd, '.rclaude'))
    expect(readFileSync(join(cwd, '.rclaude', 'project', 'card.md'), 'utf8')).toBe('kept\n')

    rmSync(cwd, { recursive: true, force: true })
  })
})
