/**
 * `.rclaude/.gitignore` must describe rules that actually fire.
 *
 * WHY THIS EXISTS (2026-08-21): the generated file said `!project/` and
 * `!rclaude.json` under a comment reading "Keep project board and config
 * committed". Those negations had never once taken effect in any project. A
 * parent .gitignore excluding the `.rclaude/` DIRECTORY stops git descending
 * into it at all, so the file was not read; and even standalone, an unanchored
 * pattern would have re-matched every file nested under `project/`.
 *
 * So the last test here is the one that matters: it hands the generated bytes
 * to real git and asks what git would actually stage. A .gitignore assertion
 * that only compares strings can pass while the rule does nothing, which is the
 * precise failure being guarded against.
 */

import { describe, expect, it } from 'bun:test'
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
import { ensureRclaudeDir } from './ensure-rclaude-dir'

const STALE =
  '# Auto-generated by rclaude\n# Session temp files\nsettings/\n\n# Keep project board and config committed\n!project/\n!rclaude.json\n'

function scratch(): string {
  return mkdtempSync(join(tmpdir(), 'ensure-rclaude-'))
}

function gitignoreOf(cwd: string): string {
  return readFileSync(join(cwd, '.rclaude', '.gitignore'), 'utf8')
}

describe('ensureRclaudeDir', () => {
  it('writes an anchored board .gitignore into a fresh project', () => {
    const cwd = scratch()
    ensureRclaudeDir(cwd)
    const written = gitignoreOf(cwd)
    expect(written).toContain('/*')
    expect(written).toContain('!/project/')
    expect(written).toContain('!/rclaude.json')
    rmSync(cwd, { recursive: true, force: true })
  })

  it('replaces the known-broken generation in place', () => {
    const cwd = scratch()
    mkdirSync(join(cwd, '.rclaude'), { recursive: true })
    writeFileSync(join(cwd, '.rclaude', '.gitignore'), STALE)
    ensureRclaudeDir(cwd)
    expect(gitignoreOf(cwd)).not.toBe(STALE)
    rmSync(cwd, { recursive: true, force: true })
  })

  it('never clobbers a hand-edited file', () => {
    const cwd = scratch()
    mkdirSync(join(cwd, '.rclaude'), { recursive: true })
    const mine = '# mine\nsettings/\n'
    writeFileSync(join(cwd, '.rclaude', '.gitignore'), mine)
    ensureRclaudeDir(cwd)
    expect(gitignoreOf(cwd)).toBe(mine)
    rmSync(cwd, { recursive: true, force: true })
  })

  it('produces rules real git honours: board in, session files out', () => {
    const cwd = scratch()
    const run = (...args: string[]) =>
      Bun.spawnSync(['git', '-c', 'core.excludesFile=', ...args], {
        cwd,
        env: { ...process.env, GIT_CONFIG_GLOBAL: '/dev/null', GIT_CONFIG_SYSTEM: '/dev/null' },
      })
    run('init', '--quiet', '.')
    ensureRclaudeDir(cwd)
    // A parent that excludes the CONTENTS, which is what the generated file
    // documents as its precondition.
    writeFileSync(join(cwd, '.gitignore'), '.rclaude/*\n!.rclaude/project/\n!.rclaude/rclaude.json\n')
    for (const rel of [
      '.rclaude/project/cards/a-card.md',
      '.rclaude/project/epics/e/log.md',
      '.rclaude/rclaude.json',
      '.rclaude/settings/agent/settings.json',
      '.rclaude/headless-abc.ndjsonl',
      '.rclaude/mcp-abc.json',
    ]) {
      mkdirSync(dirname(join(cwd, rel)), { recursive: true })
      writeFileSync(join(cwd, rel), 'x\n')
    }

    const offered = run('status', '--porcelain', '--untracked-files=all')
      .stdout.toString()
      .split('\n')
      .filter(Boolean)
      .map(l => l.slice(3).trim())

    expect(offered).toContain('.rclaude/project/cards/a-card.md')
    expect(offered).toContain('.rclaude/project/epics/e/log.md')
    expect(offered).toContain('.rclaude/rclaude.json')
    expect(
      offered.filter(
        p => p.startsWith('.rclaude/') && !p.startsWith('.rclaude/project/') && p !== '.rclaude/rclaude.json',
      ),
    ).toEqual([])
    rmSync(cwd, { recursive: true, force: true })
  })
})
