/**
 * The epic run artifact -- `run.md`: flat frontmatter (EpicRunMeta) and NOTHING
 * ELSE. The prose digest the overseer rewrites each generation ("where this epic
 * stands") lives in `digest.md` beside it.
 *
 * WHY THEY ARE TWO FILES, because one file is the obvious design and it failed:
 * the digest was `run.md`'s body, and the overseer prompt orders a rewrite of it
 * every generation. `epic_run` has no verb for "rewrite only the body", so the
 * only mechanism an overseer had was writing the whole file -- and the whole file
 * carries `gen`. On 2026-08-20 `epic-the-wall-ii` bumped its own counter that
 * way: the card said `overseer_gen: 11` and `run.md` said `gen: 12`. The wake
 * quotes the run (`epic-beat.ts`), the CAS compares the card (`epic-lease.ts`),
 * a refusal writes nothing, and the run beat every 45 seconds for hours spawning
 * nothing while every panel surface said RUNNING. Re-arming does not recover it,
 * because `startEpicRun` preserves `gen` -- only `break_lease --force` escapes.
 *
 * Splitting the files makes the whole class impossible rather than unlikely: the
 * writer of the prose no longer has the scalars in its hands.
 *
 * Same storage subset as every other artifact here (frontmatter.ts: flat scalars
 * only), and for the same reason -- these files are read by humans mid-run and
 * by a `cat` in a prompt, so nesting would buy nothing and cost legibility.
 *
 * The run file is the ONLY mutable run state. The baton beside it is append-only,
 * and the board cards are owned by the board. Keeping the mutable part small is
 * what makes a crashed generation recoverable: re-read three scalars, re-derive
 * everything else from the board.
 */

import { existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from 'node:fs'
import {
  deletedEpicDir,
  deletedEpicsRoot,
  epicDigestFile,
  epicDir,
  epicRunFile,
  nowIso,
  safeEpicId,
} from './epic-paths'
import {
  EPIC_RUN_DEFAULTS,
  type EpicCadence,
  type EpicRunFull,
  type EpicRunMeta,
  type EpicRunStatus,
} from './epic-run-types'
import { parseWhen, serializeWhen } from './epic-when'
import { parseFrontmatter, serializeFrontmatter } from './frontmatter'

const STATUSES: readonly EpicRunStatus[] = ['armed', 'running', 'paused', 'complete', 'aborted']
const TARGETS = ['pr', 'merged', 'shipped'] as const

const DEFAULT_DIGEST = '_No digest yet -- the first overseer generation writes it._'

/**
 * `run.md`'s ENTIRE body, and the sign on the door.
 *
 * An agent that opens this file has to be told, in the file, that the thing it
 * came to rewrite is not here -- otherwise the very next overseer with a prose
 * update writes it into the body it just found empty, and the counter goes with
 * it. Exported because the test asserts the banner is what a fresh run carries
 * and, separately, that it never reads back OUT as a digest.
 */
export const RUN_FILE_BANNER = [
  '<!--',
  'MACHINE-OWNED. Written by the epic engine; do not edit this file by hand.',
  'The frontmatter above is run state the engine compares (`gen` in particular),',
  'and an edit that rewrites it deadlocks the run.',
  '',
  'Looking for the digest? It is `digest.md`, beside this file. That one is yours.',
  '-->',
].join('\n')

function pick<T extends string>(v: unknown, allowed: readonly T[], fallback: T): T {
  return allowed.includes(v as T) ? (v as T) : fallback
}

function num(v: unknown, fallback: number): number {
  const n = typeof v === 'number' ? v : Number.parseInt(String(v ?? ''), 10)
  return Number.isFinite(n) ? n : fallback
}

/**
 * The same read for a field that has a FRACTIONAL part. Money does.
 *
 * `num` above parses with `parseInt`, which was correct while every scalar on a
 * run was a counter -- and silently truncates `31.40` to `31` the moment one is
 * not. For the spend ledger that rounds TOWARD ZERO, so the run under-reports
 * what it cost and the cap trips late, which is the one direction a brake must
 * never be wrong in.
 */
function dec(v: unknown, fallback: number): number {
  const n = typeof v === 'number' ? v : Number.parseFloat(String(v ?? ''))
  return Number.isFinite(n) ? n : fallback
}

/** Frontmatter is flat scalars, so a bool may arrive as a real boolean OR as the
 *  string a YAML round-trip left behind. Absent falls back, not to false. */
function bool(v: unknown, fallback: boolean): boolean {
  if (typeof v === 'boolean') return v
  if (v === 'true') return true
  if (v === 'false') return false
  return fallback
}

/** Alias, deliberately: the on-disk run and the wire run are the same shape. */
export type EpicRun = EpicRunFull

function readIfPresent(file: string): string | null {
  if (!existsSync(file)) return null
  try {
    return readFileSync(file, 'utf8')
  } catch {
    return null
  }
}

/**
 * The digest: `digest.md` first, `run.md`'s body second.
 *
 * THE FALLBACK IS THE MIGRATION. Every run armed before the split keeps its
 * digest in the run body and has no `digest.md` at all, and those runs are LIVE
 * -- reading them as "no digest yet" would hand the next generation a blank page
 * and lose the plan of record. `writeRun` completes the move on the next write.
 *
 * The banner is filtered out because it is not prose anybody wrote: once a run
 * has been written by this version, its body says only "machine-owned", and a
 * `digest.md` deleted by hand would otherwise resurrect that notice as the
 * epic's plan of record.
 */
function readDigest(root: string, epicId: string, runBody: string): string {
  const own = readIfPresent(epicDigestFile(root, epicId))?.trim()
  if (own) return own
  const legacy = runBody.replace(RUN_FILE_BANNER, '').trim()
  return legacy || DEFAULT_DIGEST
}

/** Read a run, or null when the epic has never been started. */
export function readEpicRun(root: string, epicId: string): EpicRun | null {
  const content = readIfPresent(epicRunFile(root, epicId))
  if (content === null) return null
  const { meta, body } = parseFrontmatter(content)
  return {
    epicId: typeof meta.epicId === 'string' ? meta.epicId : epicId,
    project: typeof meta.project === 'string' ? meta.project : '',
    // THE `when` AXIS, and the one field here that is not a `pick`: it reads a
    // bare scalar (every run.md written before the axis could hold more than one
    // gate), an inline array, and a joined string, all into one normalised list.
    // A run armed before `queue` existed therefore reads as exactly what it was.
    cadence: parseWhen(meta.cadence),
    status: pick(meta.status, STATUSES, 'armed'),
    gen: num(meta.gen, 0),
    target: pick(meta.target, TARGETS, EPIC_RUN_DEFAULTS.target),
    dryGens: num(meta.dryGens, 0),
    maxGens: num(meta.maxGens, EPIC_RUN_DEFAULTS.maxGens),
    // A run armed before the caps existed carries neither ceiling, and reads as
    // CAPPED AT THE DEFAULT rather than as uncapped. Falling back to 0 would
    // silently grandfather every long-lived run into the exact state this file's
    // ceilings exist to end.
    maxUsd: dec(meta.maxUsd, EPIC_RUN_DEFAULTS.maxUsd),
    maxWallClockMinutes: num(meta.maxWallClockMinutes, EPIC_RUN_DEFAULTS.maxWallClockMinutes),
    spentUsd: dec(meta.spentUsd, 0),
    concurrency: num(meta.concurrency, EPIC_RUN_DEFAULTS.concurrency),
    // A run armed before the planning stage existed carries neither field. It
    // reads as ALREADY PLANNED rather than as owing a plan: retro-fitting a
    // planning generation onto a run that is mid-flight would rewrite a board
    // its own workers are holding open.
    plan: bool(meta.plan, false),
    planned: bool(meta.planned, true),
    created: typeof meta.created === 'string' ? meta.created : '',
    updated: typeof meta.updated === 'string' ? meta.updated : '',
    ...(typeof meta.startedAt === 'string' && meta.startedAt ? { startedAt: meta.startedAt } : {}),
    ...(typeof meta.planBaseline === 'string' && meta.planBaseline ? { planBaseline: meta.planBaseline } : {}),
    ...(typeof meta.abortReason === 'string' && meta.abortReason ? { abortReason: meta.abortReason } : {}),
    ...(typeof meta.acknowledgedAt === 'string' && meta.acknowledgedAt ? { acknowledgedAt: meta.acknowledgedAt } : {}),
    digest: readDigest(root, epicId, body),
  }
}

/**
 * Write the run. `run.md` gets frontmatter and the banner, every time.
 *
 * `digest.md` is written only when this call MEANS to write prose -- when the
 * caller passed one, or when there is no digest file yet and the run is carrying
 * a legacy body across. Any other write leaves those bytes untouched, and that
 * is the second half of the fix rather than an optimisation:
 *
 * the engine patches a run by read-merge-write, so an overseer that rewrote
 * `digest.md` in the window between the read and the write would have its prose
 * silently reverted to whatever the engine happened to read. Same collision as
 * the one this file exists to end, pointing the other way. A writer that never
 * writes prose it was not given cannot lose prose it never saw.
 */
function writeRun(root: string, run: EpicRun, digest?: string): EpicRun {
  mkdirSync(epicDir(root, run.epicId), { recursive: true })
  const { digest: _prose, ...meta } = run
  // The gate list goes back as a bare scalar when there is only one of it, so a
  // run that never touched this axis keeps the exact bytes it has always had.
  const frontmatter = { ...meta, cadence: serializeWhen(run.cadence) }
  writeFileSync(epicRunFile(root, run.epicId), serializeFrontmatter(frontmatter, RUN_FILE_BANNER), 'utf8')

  const file = epicDigestFile(root, run.epicId)
  const prose = digest ?? (existsSync(file) ? null : run.digest)
  if (prose !== null) writeFileSync(file, `${prose.trim()}\n`, 'utf8')
  return run
}

export interface StartEpicRunInput {
  epicId: string
  project: string
  /**
   * The `when` axis, in whatever spelling the caller sent -- one gate, a list, or
   * a joined string. Normalised by `parseWhen`; absent leaves the run's existing
   * gates alone, which is what makes `start` a merge rather than a clobber.
   */
  cadence?: EpicCadence | EpicCadence[] | string
  target?: EpicRun['target']
  concurrency?: number
  maxGens?: number
  /** Cumulative USD ceiling. `0` disarms it. Honoured on a RESUME too -- raising
   *  it is exactly how a human says "yes, keep going" to a run that parked on
   *  budget, and the alternative would be editing run.md by hand. */
  maxUsd?: number
  /** Minutes-since-first-dispatch ceiling. `0` disarms it. Same resume rule. */
  maxWallClockMinutes?: number
  /** Run a planning generation before beat 1. Only consulted on a FRESH run --
   *  see `startEpicRun` for why a resume never re-plans. */
  plan?: boolean
}

/**
 * Arm a run. Re-arming an existing run RESUMES it (paused/complete -> armed)
 * rather than resetting the generation counter -- the baton already holds those
 * beats, and restarting the count would make two different beats share an id.
 *
 * A RESUME NEVER RE-PLANS, and that is deliberate: gen 0 already ran, the
 * overseer's own replan step covers drift from there, and re-planning would burn
 * a generation churning cards that live workers may be holding open. The `plan`
 * input is therefore only consulted when there is no existing run.
 */
export function startEpicRun(root: string, input: StartEpicRunInput, nowMs: number): EpicRun {
  safeEpicId(input.epicId)
  const ts = nowIso(nowMs)
  const existing = readEpicRun(root, input.epicId)
  const wantsPlan = input.plan ?? EPIC_RUN_DEFAULTS.plan
  const base: EpicRun = existing ?? {
    epicId: input.epicId,
    project: input.project,
    // COPIED, never shared: `EPIC_RUN_DEFAULTS.cadence` is one array instance and
    // handing it to every fresh run would make them all the same object.
    cadence: [...EPIC_RUN_DEFAULTS.cadence],
    status: 'armed',
    gen: 0,
    target: EPIC_RUN_DEFAULTS.target,
    dryGens: 0,
    maxGens: EPIC_RUN_DEFAULTS.maxGens,
    maxUsd: EPIC_RUN_DEFAULTS.maxUsd,
    maxWallClockMinutes: EPIC_RUN_DEFAULTS.maxWallClockMinutes,
    spentUsd: 0,
    concurrency: EPIC_RUN_DEFAULTS.concurrency,
    plan: wantsPlan,
    planned: !wantsPlan,
    created: ts,
    updated: ts,
    digest: DEFAULT_DIGEST,
  }
  return writeRun(root, {
    ...base,
    project: input.project || base.project,
    cadence: input.cadence === undefined ? base.cadence : parseWhen(input.cadence),
    target: input.target ?? base.target,
    concurrency: input.concurrency ?? base.concurrency,
    maxGens: input.maxGens ?? base.maxGens,
    maxUsd: input.maxUsd ?? base.maxUsd,
    maxWallClockMinutes: input.maxWallClockMinutes ?? base.maxWallClockMinutes,
    status: 'armed',
    dryGens: 0,
    // THE CLOCK RESTARTS, THE LEDGER DOES NOT. They are different kinds of fact:
    // wall clock measures the current unattended stretch, so a human resuming a
    // parked run is starting a new one and gets a fresh budget of minutes. Spend
    // is cumulative for the life of the run and re-arming must never launder it
    // -- a run that parked at $100 and resumes unchanged parks again on the next
    // beat, which is the brake working. Raise `maxUsd` to mean "keep going".
    startedAt: undefined,
    updated: ts,
    abortReason: undefined,
    // A RUN THAT STARTED AGAIN IS NEWS AGAIN. Leaving the acknowledgement on a
    // re-armed run would keep it off the wall while it was genuinely running,
    // which is the exact invisibility O2 exists to prevent.
    acknowledgedAt: undefined,
  })
}

export type EpicRunPatch = Partial<Omit<EpicRunMeta, 'epicId' | 'created'>> & { digest?: string }

/**
 * Merge a patch into an existing run. Absent fields are left untouched, and
 * `digest` is the field where that has teeth: a patch that does not name it does
 * not open `digest.md` at all, so a beat bumping `gen` can never revert prose an
 * overseer wrote a second earlier. See `writeRun`.
 */
export function patchEpicRun(root: string, epicId: string, patch: EpicRunPatch, nowMs: number): EpicRun | null {
  const current = readEpicRun(root, epicId)
  if (!current) return null
  return writeRun(root, { ...current, ...patch, updated: nowIso(nowMs) }, patch.digest)
}

/**
 * DELETE A RUN -- AND `delete` IS A MOVE, NOT AN `rm`.
 *
 * The whole tree (`run.md`, the baton, anything a later card puts beside them)
 * is relocated to `.deleted/<id>-<stamp>/`. That is what lets this verb exist at
 * all: `epic-run-no-dismiss-or-delete` refused a delete on 2026-08-20 because
 * "deleting the artifact destroys the run's history, which is the record
 * `epic-mode-engine` exists to keep", and that argument has not become wrong. A
 * move satisfies both sides -- the run is gone from every surface, and a
 * mistaken delete is one `mv` away from being undone.
 *
 * Cheap enough to be the default: all six run directories on this box measured
 * 1.7 MB in total on 2026-08-21. There is no storage argument here and there
 * never will be at this scale.
 *
 * Returns the tombstone directory, or null when the epic had nothing on disk --
 * a null is "nothing to delete", never "deleted successfully".
 */
export function deleteEpicRun(root: string, epicId: string, nowMs: number): string | null {
  const from = epicDir(root, epicId)
  if (!existsSync(from)) return null
  const to = deletedEpicDir(root, epicId, nowMs)
  mkdirSync(deletedEpicsRoot(root), { recursive: true })
  renameSync(from, to)
  return to
}

/** Has this run exhausted its generation ceiling? The runaway backstop. */
export function isOutOfGenerations(run: EpicRun): boolean {
  return run.gen >= run.maxGens
}
