/**
 * The epic run artifact -- `run.md`: flat frontmatter (EpicRunMeta) and NOTHING
 * ELSE. The prose digest the werk-master rewrites each generation ("where this epic
 * stands") lives in `digest.md` beside it.
 *
 * WHY THEY ARE TWO FILES, because one file is the obvious design and it failed:
 * the digest was `run.md`'s body, and the werk-master prompt orders a rewrite of it
 * every generation. `epic_run` has no verb for "rewrite only the body", so the
 * only mechanism a werk-master had was writing the whole file -- and the whole file
 * carried `gen`. On 2026-08-20 `epic-the-wall-ii` bumped its own counter that
 * way: the card said `overseer_gen: 11` and `run.md` said `gen: 12`. The wake
 * quoted the run (`epic-beat.ts`), the CAS compared the card (`epic-lease.ts`),
 * a refusal writes nothing, and the run beat every 45 seconds for hours spawning
 * nothing while every panel surface said RUNNING.
 *
 * Splitting the files makes the whole class impossible rather than unlikely: the
 * writer of the prose no longer has the scalars in its hands.
 *
 * AND `gen` IS NOT ONE OF THE SCALARS ANY MORE. Splitting the files closed the
 * one route a drifting mirror was known to take; deleting the mirror closes the
 * rest. The generation lives on the epic CARD (`overseer_gen`), which is what
 * the CAS compares, and nothing here reads or writes it -- a `gen:` key left in
 * an old `run.md` is inert text that the next write drops. See
 * `EpicRunReading` for the projection every surface actually renders.
 *
 * Same storage subset as every other artifact here (frontmatter.ts: flat scalars
 * only), and for the same reason -- these files are read by humans mid-run and
 * by a `cat` in a prompt, so nesting would buy nothing and cost legibility.
 *
 * The run file is the ONLY mutable run state. The baton beside it is append-only,
 * and the board cards are owned by the board. Keeping the mutable part small is
 * what makes a crashed generation recoverable: re-read three scalars, re-derive
 * everything else from the board.
 */

import { existsSync, mkdirSync, readFileSync, renameSync } from 'node:fs'
import { writeFileAtomic } from './atomic-write'
import {
  deletedEpicDir,
  deletedEpicsRoot,
  epicDigestFile,
  epicDir,
  epicRunFile,
  nowIso,
  safeEpicId,
} from './epic-paths'
import {
  EPIC_RUN_DEFAULTS,
  type EpicCadence,
  type EpicRunFull,
  type EpicRunMeta,
  type EpicRunStatus,
} from './epic-run-types'
import { parseWhen, serializeWhen } from './epic-when'
import { type Frontmatter, parseFrontmatter, serializeFrontmatter } from './frontmatter'

const STATUSES: readonly EpicRunStatus[] = ['armed', 'running', 'paused', 'complete', 'aborted']
const TARGETS = ['pr', 'merged', 'shipped'] as const

const DEFAULT_DIGEST = '_No digest yet -- the first werk-master generation writes it._'

/**
 * `run.md`'s ENTIRE body, and the sign on the door.
 *
 * An agent that opens this file has to be told, in the file, that the thing it
 * came to rewrite is not here -- otherwise the very next werk-master with a prose
 * update writes it into the body it just found empty, and the counter goes with
 * it. Exported because the test asserts the banner is what a fresh run carries
 * and, separately, that it never reads back OUT as a digest.
 */
export const RUN_FILE_BANNER = [
  '<!--',
  'MACHINE-OWNED. Written by the epic engine; do not edit this file by hand.',
  'The frontmatter above is run state the engine reads every beat -- the ceilings,',
  'the spend ledger and the `when` axis -- and an edit that rewrites it is silently',
  'clobbered by the next write. The werk-master generation is NOT here: it lives on the',
  'epic card as `overseer_gen`, which is the only copy of it there is.',
  '',
  'Looking for the digest? It is `digest.md`, beside this file. That one is yours.',
  '-->',
].join('\n')

function pick<T extends string>(v: unknown, allowed: readonly T[], fallback: T): T {
  return allowed.includes(v as T) ? (v as T) : fallback
}

function num(v: unknown, fallback: number): number {
  const n = typeof v === 'number' ? v : Number.parseInt(String(v ?? ''), 10)
  return Number.isFinite(n) ? n : fallback
}

/**
 * The same read for a field that has a FRACTIONAL part. Money does.
 *
 * `num` above parses with `parseInt`, which was correct while every scalar on a
 * run was a counter -- and silently truncates `31.40` to `31` the moment one is
 * not. For the spend ledger that rounds TOWARD ZERO, so the run under-reports
 * what it cost and the cap trips late, which is the one direction a brake must
 * never be wrong in.
 */
function dec(v: unknown, fallback: number): number {
  const n = typeof v === 'number' ? v : Number.parseFloat(String(v ?? ''))
  return Number.isFinite(n) ? n : fallback
}

/** Frontmatter is flat scalars, so a bool may arrive as a real boolean OR as the
 *  string a YAML round-trip left behind. Absent falls back, not to false. */
function bool(v: unknown, fallback: boolean): boolean {
  if (typeof v === 'boolean') return v
  if (v === 'true') return true
  if (v === 'false') return false
  return fallback
}

/** Alias, deliberately: the on-disk run and the wire run are the same shape. */
export type EpicRun = EpicRunFull

function readIfPresent(file: string): string | null {
  if (!existsSync(file)) return null
  try {
    return readFileSync(file, 'utf8')
  } catch {
    return null
  }
}

/**
 * The digest: `digest.md` first, `run.md`'s body second.
 *
 * THE FALLBACK IS THE MIGRATION. Every run armed before the split keeps its
 * digest in the run body and has no `digest.md` at all, and those runs are LIVE
 * -- reading them as "no digest yet" would hand the next generation a blank page
 * and lose the plan of record. `writeRun` completes the move on the next write.
 *
 * The banner is filtered out because it is not prose anybody wrote: once a run
 * has been written by this version, its body says only "machine-owned", and a
 * `digest.md` deleted by hand would otherwise resurrect that notice as the
 * epic's plan of record.
 */
function readDigest(root: string, epicId: string, runBody: string): string {
  const own = readIfPresent(epicDigestFile(root, epicId))?.trim()
  if (own) return own
  const legacy = runBody.replace(RUN_FILE_BANNER, '').trim()
  return legacy || DEFAULT_DIGEST
}

/**
 * THE RUN FILE IS THERE AND CANNOT BE BELIEVED.
 *
 * The third outcome of a read, and the one that used to be missing. `readEpicRun`
 * had two -- absent (`null`) and parsed -- and coerced every field through a
 * fallback on the way out, so a `run.md` truncated mid-frontmatter parsed to
 * `{ meta: {} }` and came back as `status: armed` with every counter at zero. A
 * VALID-LOOKING FRESH RUN. At generation 0 with `plan: true` and no
 * `planBaseline` that is exactly the shape `planningBeat` dispatches a PLANNING
 * GENERATION for (`epic-beat.ts`) -- a full replan over a board whose live run
 * had just lost its state, with nothing thrown and nothing logged.
 *
 * IT IS AN EXCEPTION RATHER THAN A THIRD RETURN VALUE, and that is the whole
 * design: every sentinel op goes through `runGuarded` (`epic-handlers.ts`), which
 * turns a throw into `{ ok: false, error }`, which `toEpicRunView` turns into a
 * view with no run and an error, which `runEpicBeat` already reports as "run
 * artifact NOT READ -- the read failed" and refuses to act on. So one throw
 * makes EVERY verb refuse -- `get`, `patch`, `lease`, `clear`, `delete` and
 * `start` alike -- instead of six call sites each remembering to check a flag.
 *
 * `start` refusing is a feature, not collateral damage: `startEpicRun` merges
 * onto whatever it reads, so on a torn file it would have written the defaults
 * back out as a real fresh run and laundered the corruption into the record.
 *
 * RECOVERY IS BY HAND, deliberately, and it is one command: move the torn
 * `run.md` aside (the baton beside it is intact -- it is append-only and its
 * reader skips a torn tail) and re-arm the epic. Nothing in the engine may
 * decide on its own that a run's state is disposable.
 */
export class EpicRunUnreadableError extends Error {
  constructor(epicId: string, why: string) {
    super(
      `epic run artifact for \`${epicId}\` is UNREADABLE (${why}) -- it is truncated or corrupt. ` +
        `Refusing to read it as a fresh run; move run.md aside and re-arm the epic.`,
    )
    this.name = 'EpicRunUnreadableError'
  }
}

/**
 * ALL THREE OUTCOMES OF OPENING `run.md`, decided in one place: `null` when the
 * epic was never started, the parse when it is intact, a throw when it is
 * neither. Kept out of `readEpicRun` because that function is a forty-field
 * projection and the DECISION about whether to project at all is a different
 * job -- one that has to stay legible on its own.
 */
function readRunFile(root: string, epicId: string): Frontmatter | null {
  const file = epicRunFile(root, epicId)
  if (!existsSync(file)) return null
  let parsed: Frontmatter
  try {
    parsed = parseFrontmatter(readFileSync(file, 'utf8'))
  } catch (err) {
    // PRESENT AND UNREADABLE is the same answer as present and torn: the one
    // thing it is not is "this epic was never started". Swallowing the errno
    // here is what let a permissions problem read as a fresh run.
    throw new EpicRunUnreadableError(epicId, err instanceof Error ? err.message : String(err))
  }
  // A torn write can only ever leave a PREFIX of the intended bytes, and the
  // closing `---` is written after the last key -- so "no complete block" covers
  // the whole realistic truncation space, empty file included. A file that DOES
  // close its block has every scalar the writer meant to emit.
  if (!parsed.hasFrontmatter) throw new EpicRunUnreadableError(epicId, 'run.md carries no frontmatter block')
  return parsed
}

/**
 * Read a run, or null when the epic has never been started.
 *
 * THROWS `EpicRunUnreadableError` when the file is present but does not carry a
 * frontmatter block. See that class for why the third outcome cannot be a
 * fallback and cannot be a return value.
 */
export function readEpicRun(root: string, epicId: string): EpicRun | null {
  const parsed = readRunFile(root, epicId)
  if (parsed === null) return null
  const { meta, body } = parsed
  return {
    epicId: typeof meta.epicId === 'string' ? meta.epicId : epicId,
    project: typeof meta.project === 'string' ? meta.project : '',
    // THE `when` AXIS, and the one field here that is not a `pick`: it reads a
    // bare scalar (every run.md written before the axis could hold more than one
    // gate), an inline array, and a joined string, all into one normalised list.
    // A run armed before `queue` existed therefore reads as exactly what it was.
    cadence: parseWhen(meta.cadence),
    status: pick(meta.status, STATUSES, 'armed'),
    // NO `gen`. A run armed before this card carries one in its frontmatter and
    // it is READ BY NOBODY -- the authority is the card's `overseer_gen`, and a
    // second reading of a stale number is the deadlock this file's docstring
    // describes. The key disappears from disk on the next write.
    target: pick(meta.target, TARGETS, EPIC_RUN_DEFAULTS.target),
    dryGens: num(meta.dryGens, 0),
    // A run armed before the landing gate existed has escalated nobody, which is
    // exactly what an empty ledger says. No grandfathering to worry about: the
    // gate fires off the DERIVED fact, and this only ever decides whether the
    // next wake is the first or the last one.
    unlandedWoken: typeof meta.unlandedWoken === 'string' ? meta.unlandedWoken : '',
    maxGens: num(meta.maxGens, EPIC_RUN_DEFAULTS.maxGens),
    // A run armed before the caps existed carries neither ceiling, and reads as
    // CAPPED AT THE DEFAULT rather than as uncapped. Falling back to 0 would
    // silently grandfather every long-lived run into the exact state this file's
    // ceilings exist to end.
    maxUsd: dec(meta.maxUsd, EPIC_RUN_DEFAULTS.maxUsd),
    maxWallClockMinutes: num(meta.maxWallClockMinutes, EPIC_RUN_DEFAULTS.maxWallClockMinutes),
    spentUsd: dec(meta.spentUsd, 0),
    concurrency: num(meta.concurrency, EPIC_RUN_DEFAULTS.concurrency),
    // A run armed before the planning stage existed carries neither field. It
    // reads as ALREADY PLANNED rather than as owing a plan: retro-fitting a
    // planning generation onto a run that is mid-flight would rewrite a board
    // its own workers are holding open.
    plan: bool(meta.plan, false),
    planned: bool(meta.planned, true),
    created: typeof meta.created === 'string' ? meta.created : '',
    updated: typeof meta.updated === 'string' ? meta.updated : '',
    ...(typeof meta.startedAt === 'string' && meta.startedAt ? { startedAt: meta.startedAt } : {}),
    ...(typeof meta.planBaseline === 'string' && meta.planBaseline ? { planBaseline: meta.planBaseline } : {}),
    ...(typeof meta.abortReason === 'string' && meta.abortReason ? { abortReason: meta.abortReason } : {}),
    ...(typeof meta.acknowledgedAt === 'string' && meta.acknowledgedAt ? { acknowledgedAt: meta.acknowledgedAt } : {}),
    digest: readDigest(root, epicId, body),
  }
}

/**
 * Write the run. `run.md` gets frontmatter and the banner, every time.
 *
 * `digest.md` is written only when this call MEANS to write prose -- when the
 * caller passed one, or when there is no digest file yet and the run is carrying
 * a legacy body across. Any other write leaves those bytes untouched, and that
 * is the second half of the fix rather than an optimisation:
 *
 * the engine patches a run by read-merge-write, so a werk-master that rewrote
 * `digest.md` in the window between the read and the write would have its prose
 * silently reverted to whatever the engine happened to read. Same collision as
 * the one this file exists to end, pointing the other way. A writer that never
 * writes prose it was not given cannot lose prose it never saw.
 */
function writeRun(root: string, run: EpicRun, digest?: string): EpicRun {
  mkdirSync(epicDir(root, run.epicId), { recursive: true })
  const { digest: _prose, ...meta } = run
  // The gate list goes back as a bare scalar when there is only one of it, so a
  // run that never touched this axis keeps the exact bytes it has always had.
  const frontmatter = { ...meta, cadence: serializeWhen(run.cadence) }
  // TMP-AND-RENAME, both files. A bare `writeFileSync` truncates before it
  // writes, so a sentinel killed mid-write left a `run.md` that still existed
  // and no longer said anything -- and `readEpicRun` read that as a fresh armed
  // run at generation zero. See `atomic-write.ts` and `EpicRunUnreadableError`:
  // this half stops the tear, that half stops a tear from being believed.
  writeFileAtomic(epicRunFile(root, run.epicId), serializeFrontmatter(frontmatter, RUN_FILE_BANNER))

  const file = epicDigestFile(root, run.epicId)
  const prose = digest ?? (existsSync(file) ? null : run.digest)
  if (prose !== null) writeFileAtomic(file, `${prose.trim()}\n`)
  return run
}

export interface StartEpicRunInput {
  epicId: string
  project: string
  /**
   * The `when` axis, in whatever spelling the caller sent -- one gate, a list, or
   * a joined string. Normalised by `parseWhen`; absent leaves the run's existing
   * gates alone, which is what makes `start` a merge rather than a clobber.
   */
  cadence?: EpicCadence | EpicCadence[] | string
  target?: EpicRun['target']
  concurrency?: number
  maxGens?: number
  /** Cumulative USD ceiling. `0` disarms it. Honoured on a RESUME too -- raising
   *  it is exactly how a human says "yes, keep going" to a run that parked on
   *  budget, and the alternative would be editing run.md by hand. */
  maxUsd?: number
  /** Minutes-since-first-dispatch ceiling. `0` disarms it. Same resume rule. */
  maxWallClockMinutes?: number
  /** Run a planning generation before beat 1. Only consulted on a FRESH run --
   *  see `startEpicRun` for why a resume never re-plans. */
  plan?: boolean
}

/**
 * Arm a run. Re-arming an existing run RESUMES it (paused/complete -> armed)
 * rather than resetting the generation counter -- the baton already holds those
 * beats, and restarting the count would make two different beats share an id.
 * The counter is not this file's to reset in any case: it is the epic card's
 * lease, and `start` does not touch the card.
 *
 * A RESUME NEVER RE-PLANS, and that is deliberate: gen 0 already ran, the
 * werk-master's own replan step covers drift from there, and re-planning would burn
 * a generation churning cards that live workers may be holding open. The `plan`
 * input is therefore only consulted when there is no existing run.
 */
export function startEpicRun(root: string, input: StartEpicRunInput, nowMs: number): EpicRun {
  safeEpicId(input.epicId)
  const ts = nowIso(nowMs)
  const existing = readEpicRun(root, input.epicId)
  const wantsPlan = input.plan ?? EPIC_RUN_DEFAULTS.plan
  const base: EpicRun = existing ?? {
    epicId: input.epicId,
    project: input.project,
    // COPIED, never shared: `EPIC_RUN_DEFAULTS.cadence` is one array instance and
    // handing it to every fresh run would make them all the same object.
    cadence: [...EPIC_RUN_DEFAULTS.cadence],
    status: 'armed',
    target: EPIC_RUN_DEFAULTS.target,
    dryGens: 0,
    unlandedWoken: '',
    maxGens: EPIC_RUN_DEFAULTS.maxGens,
    maxUsd: EPIC_RUN_DEFAULTS.maxUsd,
    maxWallClockMinutes: EPIC_RUN_DEFAULTS.maxWallClockMinutes,
    spentUsd: 0,
    concurrency: EPIC_RUN_DEFAULTS.concurrency,
    plan: wantsPlan,
    planned: !wantsPlan,
    created: ts,
    updated: ts,
    digest: DEFAULT_DIGEST,
  }
  return writeRun(root, {
    ...base,
    project: input.project || base.project,
    cadence: input.cadence === undefined ? base.cadence : parseWhen(input.cadence),
    target: input.target ?? base.target,
    concurrency: input.concurrency ?? base.concurrency,
    maxGens: input.maxGens ?? base.maxGens,
    maxUsd: input.maxUsd ?? base.maxUsd,
    maxWallClockMinutes: input.maxWallClockMinutes ?? base.maxWallClockMinutes,
    status: 'armed',
    dryGens: 0,
    // A RESUME IS A FRESH ASK. The escalation ledger records that somebody was
    // already told about a branch and did not merge it -- which parks the run on
    // the second sighting. A human re-arming a parked run is that human saying
    // "try again", and carrying the old ledger across would park it on the very
    // first beat for a card the resume exists to give another go.
    unlandedWoken: '',
    // THE CLOCK RESTARTS, THE LEDGER DOES NOT. They are different kinds of fact:
    // wall clock measures the current unattended stretch, so a human resuming a
    // parked run is starting a new one and gets a fresh budget of minutes. Spend
    // is cumulative for the life of the run and re-arming must never launder it
    // -- a run that parked at $100 and resumes unchanged parks again on the next
    // beat, which is the brake working. Raise `maxUsd` to mean "keep going".
    startedAt: undefined,
    updated: ts,
    abortReason: undefined,
    // A RUN THAT STARTED AGAIN IS NEWS AGAIN. Leaving the acknowledgement on a
    // re-armed run would keep it off the wall while it was genuinely running,
    // which is the exact invisibility O2 exists to prevent.
    acknowledgedAt: undefined,
  })
}

export type EpicRunPatch = Partial<Omit<EpicRunMeta, 'epicId' | 'created'>> & { digest?: string }

/**
 * Merge a patch into an existing run. Absent fields are left untouched, and
 * `digest` is the field where that has teeth: a patch that does not name it does
 * not open `digest.md` at all, so a beat bumping `gen` can never revert prose an
 * werk-master wrote a second earlier. See `writeRun`.
 */
export function patchEpicRun(root: string, epicId: string, patch: EpicRunPatch, nowMs: number): EpicRun | null {
  const current = readEpicRun(root, epicId)
  if (!current) return null
  return writeRun(root, { ...current, ...patch, updated: nowIso(nowMs) }, patch.digest)
}

/**
 * DELETE A RUN -- AND `delete` IS A MOVE, NOT AN `rm`.
 *
 * The whole tree (`run.md`, the baton, anything a later card puts beside them)
 * is relocated to `.deleted/<id>-<stamp>/`. That is what lets this verb exist at
 * all: `epic-run-no-dismiss-or-delete` refused a delete on 2026-08-20 because
 * "deleting the artifact destroys the run's history, which is the record
 * `epic-mode-engine` exists to keep", and that argument has not become wrong. A
 * move satisfies both sides -- the run is gone from every surface, and a
 * mistaken delete is one `mv` away from being undone.
 *
 * Cheap enough to be the default: all six run directories on this box measured
 * 1.7 MB in total on 2026-08-21. There is no storage argument here and there
 * never will be at this scale.
 *
 * Returns the tombstone directory, or null when the epic had nothing on disk --
 * a null is "nothing to delete", never "deleted successfully".
 */
export function deleteEpicRun(root: string, epicId: string, nowMs: number): string | null {
  const from = epicDir(root, epicId)
  if (!existsSync(from)) return null
  const to = deletedEpicDir(root, epicId, nowMs)
  mkdirSync(deletedEpicsRoot(root), { recursive: true })
  renameSync(from, to)
  return to
}
