/**
 * Petname generator (plan-quest-engine §4). `floppy-panda` = an autogenerated,
 * unique, PUBLIC (not secret) adjective-animal handle -- a human AND machine
 * mnemonic + selector for a quest. Collision-checked against existing quests.
 *
 * Normal runtime code: `Math.random` is fine here (unlike broker/sentinel state
 * or workflow scripts). The generator takes a `taken` predicate so the caller
 * (quest-store) decides what "already exists" means without this file touching
 * the filesystem.
 */

// Kept short, friendly, lowercase, ASCII, single-word (slug-safe). ~54 x ~54.
const ADJECTIVES = [
  'floppy',
  'brave',
  'clever',
  'cosmic',
  'dapper',
  'eager',
  'fuzzy',
  'gentle',
  'happy',
  'jolly',
  'keen',
  'lucky',
  'mellow',
  'nimble',
  'plucky',
  'quiet',
  'rapid',
  'silly',
  'tidy',
  'witty',
  'zesty',
  'amber',
  'bold',
  'crisp',
  'dandy',
  'early',
  'fancy',
  'glad',
  'humble',
  'ideal',
  'jazzy',
  'kind',
  'lively',
  'merry',
  'noble',
  'olive',
  'proud',
  'royal',
  'sunny',
  'trusty',
  'upbeat',
  'vivid',
  'warm',
  'young',
  'zealous',
  'bright',
  'calm',
  'deft',
  'frosty',
  'golden',
  'spry',
  'swift',
  'velvet',
  'wise',
]

const ANIMALS = [
  'panda',
  'otter',
  'falcon',
  'badger',
  'cobra',
  'dingo',
  'egret',
  'ferret',
  'gecko',
  'heron',
  'ibis',
  'jackal',
  'koala',
  'lemur',
  'marmot',
  'newt',
  'ocelot',
  'puffin',
  'quail',
  'raven',
  'seal',
  'tapir',
  'urial',
  'viper',
  'walrus',
  'yak',
  'zebra',
  'beaver',
  'condor',
  'dolphin',
  'eagle',
  'finch',
  'gopher',
  'hyena',
  'iguana',
  'jaguar',
  'kestrel',
  'llama',
  'moose',
  'narwhal',
  'osprey',
  'possum',
  'rabbit',
  'shrew',
  'toucan',
  'vole',
  'weasel',
  'wombat',
  'bison',
  'crane',
  'dove',
  'fox',
  'hawk',
  'lynx',
]

function pick<T>(list: T[]): T {
  return list[Math.floor(Math.random() * list.length)]
}

/** A raw `adjective-animal` handle (no collision check). */
export function randomPetname(): string {
  return `${pick(ADJECTIVES)}-${pick(ANIMALS)}`
}

/** True if `name` is a syntactically valid petname handle. */
export function isValidPetname(name: string): boolean {
  return /^[a-z]+-[a-z]+(-[0-9]+)?$/.test(name)
}

/**
 * Generate a petname not already `taken`. Tries random adjective-animal combos;
 * after `maxTries` collisions it appends an incrementing numeric suffix so it
 * ALWAYS terminates with a unique handle (the keyspace is finite -- a busy
 * project must never wedge quest creation).
 */
export function generatePetname(taken: (name: string) => boolean, maxTries = 64): string {
  for (let i = 0; i < maxTries; i++) {
    const candidate = randomPetname()
    if (!taken(candidate)) return candidate
  }
  // Fell through: suffix a base handle until free.
  const base = randomPetname()
  for (let n = 2; ; n++) {
    const candidate = `${base}-${n}`
    if (!taken(candidate)) return candidate
  }
}
