// Auto-generated by scripts/gen-version.ts - do not edit
// Type is defined here so consumers get proper types even from stale stubs
export interface BuildVersion {
  gitHash: string
  gitHashShort: string
  buildTime: string
  dirty: boolean
  recentCommits: Array<{ hash: string; message: string }>
}

export const BUILD_VERSION: BuildVersion = {
  gitHash: '51f269801928b81b63e72359cf6ae007c605ec36',
  gitHashShort: '51f2698-dirty',
  buildTime: '2026-03-22T11:08:44.413Z',
  dirty: true,
  recentCommits: [{"hash":"51f2698","message":"(HEAD -> main, origin/main, origin/HEAD) feat: Show link status (connected/blocked) in list_sessions results"},{"hash":"bb19d7e","message":"fix: Deduplicate agent completion notifications in transcript"},{"hash":"3bbb466","message":"fix: stopImmediatePropagation on ESC in fullscreen to prevent tab switch"}],
}
