// Auto-generated by scripts/gen-version.ts - do not edit
// Type is defined here so consumers get proper types even from stale stubs
export interface BuildVersion {
  gitHash: string
  gitHashShort: string
  buildTime: string
  dirty: boolean
  branch: string
  githubRepo: string
  recentCommits: Array<{ hash: string; message: string }>
}

export const BUILD_VERSION: BuildVersion = {
  gitHash: '49d1bb19d57576c2257ce03cb8a6320a9fac9645',
  gitHashShort: '49d1bb1-dirty',
  buildTime: '2026-04-11T07:57:19.216Z',
  dirty: true,
  branch: 'main',
  githubRepo: 'claudification/remote-claude',
  recentCommits: [
    {
      hash: '49d1bb1',
      message: '(HEAD -> main) feat: show cost in collapsed session header, fix project name override',
    },
    { hash: 'dd254bf', message: 'feat: add "Cost in sidebar" toggle to dashboard settings' },
    { hash: 'a094ca0', message: 'fix: project name is primary in sidebar, session name shown underneath' },
  ],
}
