// Auto-generated by scripts/gen-version.ts - do not edit
// Type is defined here so consumers get proper types even from stale stubs
export interface BuildVersion {
  gitHash: string
  gitHashShort: string
  buildTime: string
  dirty: boolean
  recentCommits: Array<{ hash: string; message: string }>
}

export const BUILD_VERSION: BuildVersion = {
  gitHash: 'dddfefc6e973b9b9f00684d5c339aee26b8eb44c',
  gitHashShort: 'dddfefc-dirty',
  buildTime: '2026-03-30T15:35:35.290Z',
  dirty: true,
  recentCommits: [{"hash":"dddfefc","message":"(HEAD -> main, origin/main, origin/HEAD) fix: Zombie session eviction at 30 days, not 24 hours"},{"hash":"53c4862","message":"fix: Evict zombie sessions, log broadcast errors, fix resync storm"},{"hash":"7fa92d0","message":"feat: MCP tool output display with configurable line limits"}],
}
