#!/bin/bash
# Install the CLAUDEWERK commit-ledger post-commit hook into a repository.
#
#   scripts/install-git-hooks.sh [repo-path]   # install (default: this repo)
#   scripts/install-git-hooks.sh --uninstall [repo-path]
#   scripts/install-git-hooks.sh --status [repo-path]
#
# Idempotent. Hooks live in the git COMMON dir, so installing once covers the
# main checkout AND every worktree under .claude/worktrees/ -- verified:
# `git rev-parse --git-path hooks` from inside a linked worktree resolves to the
# main repo's .git/hooks.
#
# ── WHY A DISPATCHER, NOT AN APPEND ─────────────────────────────────────────
# Appending our block to an existing hook is broken in two ways that both bite
# silently, and both were live in this very repo:
#   1. The existing hook ends in `exit 0` (and short-circuits earlier still for
#      human commits). Everything appended after it NEVER RUNS.
#   2. The existing hook is `#!/bin/sh`. Our block needs bash (`<<<`, process
#      substitution, `${var//}`), which posix-mode sh does not provide.
# So we PRESERVE the prior hook as `post-commit.pre-claudewerk` and generate a
# bash dispatcher that runs it as a SUBPROCESS -- its own shebang, its own
# exits, its own failures, none of which can reach the ledger.

set -euo pipefail

MARKER="# >>> claudewerk commit-ledger >>>"
END_MARKER="# <<< claudewerk commit-ledger <<<"
PRESERVED_NAME="post-commit.pre-claudewerk"
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
SOURCE_HOOK="$SCRIPT_DIR/git-hooks/post-commit"

mode=install
repo=.
for arg in "$@"; do
  case "$arg" in
    --uninstall) mode=uninstall ;;
    --status) mode=status ;;
    -h | --help)
      grep '^#' "$0" | head -24
      exit 0
      ;;
    *) repo=$arg ;;
  esac
done

cd "$repo"
hooks_dir=$(git rev-parse --path-format=absolute --git-path hooks 2>/dev/null) || {
  echo "not a git repository: $repo" >&2
  exit 1
}
mkdir -p "$hooks_dir"
target="$hooks_dir/post-commit"
preserved="$hooks_dir/$PRESERVED_NAME"

installed() { [ -f "$target" ] && grep -qF "$MARKER" "$target"; }

case "$mode" in
  status)
    if installed; then
      echo "installed: $target"
      [ -f "$preserved" ] && echo "chained (runs first): $preserved"
    else
      echo "not installed ($target)"
    fi
    exit 0
    ;;

  uninstall)
    if ! installed; then
      echo "not installed, nothing to do"
      exit 0
    fi
    rm -f "$target"
    if [ -f "$preserved" ]; then
      mv "$preserved" "$target"
      chmod +x "$target"
      echo "removed the ledger hook and restored the previous one at $target"
    else
      echo "removed $target"
    fi
    exit 0
    ;;
esac

# ─── install ────────────────────────────────────────────────────────────────
if [ -f "$target" ] && ! installed; then
  # A foreign hook was here first. Preserve it verbatim -- the dispatcher will
  # invoke it as its own process.
  mv "$target" "$preserved"
  chmod +x "$preserved"
  echo "preserved the existing post-commit hook as $PRESERVED_NAME (it still runs, first)"
elif [ -f "$target" ] && installed && ! [ -f "$preserved" ]; then
  # An older APPEND-style install of ours. Recover whatever it wrapped, so the
  # upgrade doesn't silently eat someone's hook.
  recovered=$(mktemp)
  sed "/$MARKER/,/$END_MARKER/d" "$target" >"$recovered"
  # Anything beyond a lone shebang / blank lines is a real hook worth keeping.
  if grep -qvE '^(#!.*|#.*|\s*)$' "$recovered"; then
    mv "$recovered" "$preserved"
    chmod +x "$preserved"
    echo "recovered the hook the previous append-style install had wrapped -> $PRESERVED_NAME"
  else
    rm -f "$recovered"
  fi
fi

{
  printf '#!/bin/bash\n'
  printf '%s\n' "$MARKER"
  printf '# Generated by scripts/install-git-hooks.sh -- edit that, not this.\n\n'
  printf 'hooks_dir=$(cd "$(dirname "$0")" && pwd)\n'
  printf '# Any hook that predates the ledger runs FIRST, in its own process, so its\n'
  printf '# shebang, its early exits and its failures cannot reach the block below.\n'
  printf 'if [ -x "$hooks_dir/%s" ]; then "$hooks_dir/%s" "$@" || true; fi\n\n' "$PRESERVED_NAME" "$PRESERVED_NAME"
  tail -n +2 "$SOURCE_HOOK"
  printf '\n%s\n' "$END_MARKER"
  printf 'exit 0\n'
} >"$target"

chmod +x "$target"
echo "installed commit-ledger hook: $target"
echo "covers: $(git rev-parse --path-format=absolute --git-common-dir) (main checkout + every linked worktree)"
echo "disable without uninstalling: export RCLAUDE_COMMIT_LEDGER=0"
