#!/bin/bash
# Install the CLAUDEWERK git hooks into a repository.
#
#   scripts/install-git-hooks.sh [repo-path]   # install (default: this repo)
#   scripts/install-git-hooks.sh --uninstall [repo-path]
#   scripts/install-git-hooks.sh --status [repo-path]
#
# Two hooks, one installer, and BOTH blocks live in BOTH hooks:
#   post-commit -- the commit ledger (every commit -> broker, attributed),
#                  plus the fallow merge audit when HEAD is a MERGE commit.
#   post-merge  -- the fallow merge audit (clean and fast-forward merges),
#                  plus the commit ledger when HEAD is a MERGE commit.
#
# Idempotent. Hooks live in the git COMMON dir, so installing once covers the
# main checkout AND every worktree under .claude/worktrees/ -- verified:
# `git rev-parse --git-path hooks` from inside a linked worktree resolves to the
# main repo's .git/hooks.
#
# ── WHY A DISPATCHER, NOT AN APPEND ─────────────────────────────────────────
# Appending our block to an existing hook is broken in two ways that both bite
# silently, and both were live in this very repo:
#   1. The existing hook ends in `exit 0` (and short-circuits earlier still for
#      human commits). Everything appended after it NEVER RUNS.
#   2. The existing hook is `#!/bin/sh`. Our block needs bash (`<<<`, process
#      substitution, `${var//}`), which posix-mode sh does not provide.
# So we PRESERVE the prior hook as `<hook>.pre-claudewerk` and generate a bash
# dispatcher that runs it as a SUBPROCESS -- its own shebang, its own exits, its
# own failures, none of which can reach our blocks.
#
# ── WHY BOTH BLOCKS NEED BOTH HOOKS ─────────────────────────────────────────
# Verified empirically (see scripts/install-git-hooks.test.ts):
#   clean `git merge --no-ff`            -> post-merge fires, post-commit does NOT
#   fast-forward `git merge` / `git pull`-> post-merge fires, post-commit does NOT
#   conflict + `git merge --continue`    -> post-commit fires, post-merge does NOT
#   conflict + `git commit`              -> post-commit fires, post-merge does NOT
# Wiring only post-merge would miss exactly the conflict-resolution path, which
# is the path a fleet integrator hits most. Wiring only post-commit -- which is
# what the ledger did until gen 25 -- misses every merge that applied CLEANLY,
# i.e. the commit that actually changes `main`. Same blind spot, same cause.
#
# The ledger block in post-merge records ONLY a HEAD with 2+ parents: post-merge
# fires for a fast-forward too, and a fast-forward writes no commit here at all.
# The guard is in the ledger source, keyed off CLAUDEWERK_LEDGER_EVENT.

set -euo pipefail

LEDGER_MARKER="# >>> claudewerk commit-ledger >>>"
LEDGER_END="# <<< claudewerk commit-ledger <<<"
MERGE_MARKER="# >>> claudewerk fallow-merge-warn >>>"
MERGE_END="# <<< claudewerk fallow-merge-warn <<<"
# Stamped into every dispatcher we generate. Its ABSENCE is how we recognise a
# pre-dispatcher append-style install, which is the only thing worth recovering.
GEN_MARKER="# Generated by scripts/install-git-hooks.sh"
WARN_SCRIPT="fallow-merge-warn.sh"
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
LEDGER_SOURCE="$SCRIPT_DIR/git-hooks/post-commit"
MERGE_SOURCE="$SCRIPT_DIR/git-hooks/post-merge"
WARN_SOURCE="$SCRIPT_DIR/git-hooks/$WARN_SCRIPT"

mode=install
repo=.
for arg in "$@"; do
  case "$arg" in
    --uninstall) mode=uninstall ;;
    --status) mode=status ;;
    -h | --help)
      grep '^#' "$0" | head -40
      exit 0
      ;;
    *) repo=$arg ;;
  esac
done

cd "$repo"
hooks_dir=$(git rev-parse --path-format=absolute --git-path hooks 2>/dev/null) || {
  echo "not a git repository: $repo" >&2
  exit 1
}
mkdir -p "$hooks_dir"

# Is OUR dispatcher at $1 (a hook name)? Marker $2.
installed() { [ -f "$hooks_dir/$1" ] && grep -qF "$2" "$hooks_dir/$1"; }

# A hook that was here before us gets preserved verbatim; the dispatcher invokes
# it as its own process. Also recovers whatever an older APPEND-style install of
# ours had wrapped, so an upgrade never silently eats someone's hook.
preserve_foreign() {
  local name=$1 marker=$2
  local target="$hooks_dir/$name" preserved="$hooks_dir/$name.pre-claudewerk"
  if [ -f "$target" ] && ! installed "$name" "$marker"; then
    mv "$target" "$preserved"
    chmod +x "$preserved"
    echo "preserved the existing $name hook as $name.pre-claudewerk (it still runs, first)"
  elif [ -f "$target" ] && installed "$name" "$marker" && ! [ -f "$preserved" ] &&
    ! grep -qF "$GEN_MARKER" "$target"; then
    # An older APPEND-style install of ours: a foreign hook with our block glued
    # on. One of OUR dispatchers is excluded by the GEN_MARKER test above --
    # without it a plain re-install "recovers" its own preamble as a foreign hook.
    local recovered
    recovered=$(mktemp)
    sed -e "/$LEDGER_MARKER/,/$LEDGER_END/d" -e "/$MERGE_MARKER/,/$MERGE_END/d" "$target" >"$recovered"
    # Anything beyond a lone shebang / comments / blank lines / `exit 0` is a real hook.
    if grep -qvE '^(#!.*|#.*|exit 0|[[:space:]]*)$' "$recovered"; then
      mv "$recovered" "$preserved"
      chmod +x "$preserved"
      echo "recovered the hook the previous append-style install had wrapped -> $name.pre-claudewerk"
    else
      rm -f "$recovered"
    fi
  fi
}

dispatcher_preamble() {
  local name=$1
  printf '#!/bin/bash\n'
  printf '# Generated by scripts/install-git-hooks.sh -- edit that, not this.\n\n'
  printf 'hooks_dir=$(cd "$(dirname "$0")" && pwd)\n'
  printf '# Any hook that predates ours runs FIRST, in its own process, so its\n'
  printf '# shebang, its early exits and its failures cannot reach the blocks below.\n'
  printf 'if [ -x "$hooks_dir/%s.pre-claudewerk" ]; then "$hooks_dir/%s.pre-claudewerk" "$@" || true; fi\n\n' "$name" "$name"
}

restore_or_remove() {
  local name=$1
  local target="$hooks_dir/$name" preserved="$hooks_dir/$name.pre-claudewerk"
  rm -f "$target"
  if [ -f "$preserved" ]; then
    mv "$preserved" "$target"
    chmod +x "$target"
    echo "removed the claudewerk $name hook and restored the previous one at $target"
  else
    echo "removed $target"
  fi
}

case "$mode" in
  status)
    if installed post-commit "$LEDGER_MARKER"; then
      echo "installed: $hooks_dir/post-commit (commit ledger)"
      if grep -qF "$MERGE_MARKER" "$hooks_dir/post-commit"; then
        echo "           + fallow merge audit on merge commits"
      fi
      if [ -f "$hooks_dir/post-commit.pre-claudewerk" ]; then
        echo "  chained (runs first): $hooks_dir/post-commit.pre-claudewerk"
      fi
    else
      echo "not installed ($hooks_dir/post-commit)"
    fi
    if installed post-merge "$MERGE_MARKER"; then
      echo "installed: $hooks_dir/post-merge (fallow merge audit)"
      if grep -qF "$LEDGER_MARKER" "$hooks_dir/post-merge"; then
        echo "           + commit ledger on merge commits"
      else
        echo "           MISSING the commit ledger -- a clean merge goes unrecorded; re-run the installer"
      fi
      if [ -f "$hooks_dir/post-merge.pre-claudewerk" ]; then
        echo "  chained (runs first): $hooks_dir/post-merge.pre-claudewerk"
      fi
    else
      echo "not installed ($hooks_dir/post-merge)"
    fi
    if [ -f "$hooks_dir/$WARN_SCRIPT" ]; then
      if cmp -s "$hooks_dir/$WARN_SCRIPT" "$WARN_SOURCE"; then
        echo "installed: $hooks_dir/$WARN_SCRIPT (matches source)"
      else
        echo "STALE:     $hooks_dir/$WARN_SCRIPT differs from $WARN_SOURCE -- re-run the installer"
      fi
    else
      echo "not installed ($hooks_dir/$WARN_SCRIPT)"
    fi
    # `.claude/hooks/fallow-gate.sh` is GENERATED by `fallow setup-hooks`, which
    # overwrites it wholesale. None of the merge audit lives there -- but the
    # header note saying so does, and a regeneration silently drops it. This is
    # the marker that makes that noticeable; docs/fallow-merge-audit.md holds the
    # wording to paste back.
    gate="$(git rev-parse --show-toplevel)/.claude/hooks/fallow-gate.sh"
    if [ -f "$gate" ] && ! grep -q 'git merge' "$gate"; then
      echo "STALE:     $gate no longer documents its merge blind spot"
      echo '           -- `fallow setup-hooks` probably regenerated it; see docs/fallow-merge-audit.md'
    fi
    exit 0
    ;;

  uninstall)
    did=0
    if installed post-commit "$LEDGER_MARKER"; then
      restore_or_remove post-commit
      did=1
    fi
    if installed post-merge "$MERGE_MARKER"; then
      restore_or_remove post-merge
      did=1
    fi
    if [ -f "$hooks_dir/$WARN_SCRIPT" ]; then
      rm -f "$hooks_dir/$WARN_SCRIPT"
      echo "removed $hooks_dir/$WARN_SCRIPT"
      did=1
    fi
    if [ "$did" = 0 ]; then echo "not installed, nothing to do"; fi
    exit 0
    ;;
esac

# ─── install ────────────────────────────────────────────────────────────────
# The audit script is COPIED next to the hooks rather than referenced in the
# working tree: a hook must keep working from any linked worktree, and from a
# checkout where scripts/ is momentarily absent (bisect, detached base
# snapshot). `--status` reports when the copy has drifted from the source.
install -m 0755 "$WARN_SOURCE" "$hooks_dir/$WARN_SCRIPT"

preserve_foreign post-commit "$LEDGER_MARKER"
{
  dispatcher_preamble post-commit
  printf '%s\n' "$LEDGER_MARKER"
  tail -n +2 "$LEDGER_SOURCE"
  printf '\n%s\n\n' "$LEDGER_END"
  printf '%s\n' "$MERGE_MARKER"
  printf '# A CONFLICTED merge finished with `git merge --continue` (or a plain\n'
  printf '# `git commit`) fires post-commit and NOT post-merge. --event commit\n'
  printf '# audits only when HEAD is a merge commit; ordinary commits belong to\n'
  printf '# the PreToolUse gate, which blocks, and must not be audited twice.\n'
  printf 'if [ -x "$hooks_dir/%s" ]; then "$hooks_dir/%s" --event commit || true; fi\n' "$WARN_SCRIPT" "$WARN_SCRIPT"
  printf '%s\n' "$MERGE_END"
  printf 'exit 0\n'
} >"$hooks_dir/post-commit"
chmod +x "$hooks_dir/post-commit"

preserve_foreign post-merge "$MERGE_MARKER"
{
  dispatcher_preamble post-merge
  # The ledger goes FIRST: it backgrounds a time-capped curl and returns
  # immediately, while the audit below runs fallow synchronously for seconds.
  printf '%s\n' "$LEDGER_MARKER"
  printf '# `git post-commit` does NOT fire for a merge git completes on its own,\n'
  printf '# so a ledger wired only to post-commit records the merges that happened\n'
  printf '# to CONFLICT and no others. This is the other half.\n'
  printf '#\n'
  printf '# =merge makes the block below record only a HEAD with 2+ parents:\n'
  printf '# post-merge also fires for a fast-forward, which creates no commit here\n'
  printf '# -- those commits were authored elsewhere and are not ours to claim.\n'
  printf 'CLAUDEWERK_LEDGER_EVENT=merge\n'
  tail -n +2 "$LEDGER_SOURCE"
  printf '\n%s\n\n' "$LEDGER_END"
  printf '%s\n' "$MERGE_MARKER"
  tail -n +2 "$MERGE_SOURCE"
  printf '%s\n' "$MERGE_END"
} >"$hooks_dir/post-merge"
chmod +x "$hooks_dir/post-merge"

# `git rev-parse --git-path hooks` HONOURS core.hooksPath, so we always write
# where git will actually look -- but that cuts the other way: a GLOBAL
# core.hooksPath (a dotfiles repo, `git config --global core.hooksPath ...`)
# silently redirects this install into a directory shared by every repository on
# the machine. Say so; installing a commit ledger machine-wide is not a thing to
# discover later.
# `pwd -P`, not `pwd`: git answers with the physical path (/private/var/...)
# while a configured value keeps whatever symlink was typed (/var/...), and
# comparing logical paths reports a mismatch on every macOS temp dir.
common_dir=$(git rev-parse --path-format=absolute --git-common-dir)
if [ "$(cd "$hooks_dir" && pwd -P)" != "$(cd "$common_dir" && pwd -P)/hooks" ]; then
  scope="repo-local"
  if git config --global --get core.hooksPath >/dev/null 2>&1; then scope="GLOBAL"; fi
  echo "WARNING: a $scope core.hooksPath redirected this install to $hooks_dir," >&2
  echo "WARNING: outside $common_dir/hooks." >&2
  if [ "$scope" = "GLOBAL" ]; then
    echo "WARNING: that directory is shared -- EVERY repo on this machine now runs these hooks." >&2
  fi
fi

echo "installed commit-ledger hooks: $hooks_dir/post-commit (+ merge commits via post-merge)"
echo "installed merge-audit hooks:   $hooks_dir/post-merge (+ merge commits via post-commit)"
echo "covers: $(git rev-parse --path-format=absolute --git-common-dir) (main checkout + every linked worktree)"
echo "disable without uninstalling: export RCLAUDE_COMMIT_LEDGER=0 / RCLAUDE_FALLOW_MERGE_WARN=0"
