#!/usr/bin/env bun

/**
 * Version-control configuration does not get unit tests.
 *
 * `.gitignore`, `.gitattributes` and friends are configuration for a tool that
 * already has its own test suite. A test that shells out to `git check-ignore`
 * -- or copies our `.gitignore` into a scratch repo and asks `git status` what
 * it would stage -- is asserting that git honours git. Our code is not in the
 * call path. It can only ever fail for two reasons: git changed (it did not),
 * or somebody edited the config on purpose (in which case the test is a
 * speed bump, not a safety net).
 *
 * WHY THIS EXISTS (2026-08-21): a fleet run decided the project board belonged
 * in git, then defended that decision with 332 lines of test across two files
 * -- `board-gitignore.test.ts` and a sparse-checkout suite. The premise was
 * reverted 48 minutes later (`7ee496a4`); the tests had made a fifteen-minute
 * decision expensive to walk back. One of them survived the revert and sat RED
 * on main for hours, asserting a policy the generator had already stopped
 * emitting.
 *
 * The rule is deliberately narrow, and it is about the ASSERTION, not the word.
 * Testing code that WRITES a config file is fine -- assert the bytes you
 * generate. What is banned is handing those bytes to git and testing git's
 * reply, or reading a config file out of THIS checkout to check its contents.
 *
 * So the bans come in two classes, and the difference is whether the token can
 * appear innocently:
 *
 * - UNCONDITIONAL (`check-ignore`, `sparse-checkout`): a git invocation or a
 *   working-tree assertion by construction. There is no innocent reading, so
 *   they are a finding on sight.
 * - CONDITIONAL (`.gitignore`, `.gitattributes`): on their own these are just
 *   filenames, and a bytes assertion NEEDS the filename to find the file it is
 *   asserting on. They are a finding only when the same file also runs git or
 *   reaches into this checkout -- see `testsGitOrTheCheckout`. That is exactly
 *   the line between reading back a file our own code just wrote into a
 *   tmpdir, and asking git for its opinion.
 *
 * The two predicates over-match on purpose. A test that runs git for an
 * unrelated reason and happens to name `.gitignore` gets told to restructure;
 * that is a cheap wrong answer. Silently permitting a `git status` assertion is
 * an expensive one. There is deliberately NO suppression pragma: an opt-out
 * hands the judgment call back to whoever is writing the offending test, which
 * is the person this gate exists to stop.
 *
 * Run: `bun run scripts/lint-no-config-tests.ts`
 * Exits 0 = clean, 1 = violations found.
 */

import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { type LintFinding, reportAndExit } from './lib/lint-report'
import { scanSourceFiles } from './lib/source-files'

const ROOT = join(import.meta.dir, '..')

/** Directories whose `*.test.ts` files are subject to the rule. */
const TEST_ROOTS = ['src', 'web', 'scripts', 'packages']

interface Ban {
  /** Matched against code (comments stripped) -- a literal, not a word. */
  token: string
  /**
   * `true` = a finding wherever the token appears. `false` = a finding only in
   * a file that also satisfies `testsGitOrTheCheckout`.
   */
  unconditional: boolean
  why: string
}

const BANS: Ban[] = [
  {
    token: 'check-ignore',
    unconditional: true,
    why: 'asks git whether git ignores a path -- that is a test of git',
  },
  {
    token: 'sparse-checkout',
    unconditional: true,
    why: 'asserts a git working-tree layout, not our code',
  },
  {
    token: '.gitignore',
    unconditional: false,
    why: 'names a .gitignore in a file that also runs git or reads this checkout -- assert the bytes your generator writes, not the reply git gives',
  },
  {
    token: '.gitattributes',
    unconditional: false,
    why: 'names a .gitattributes in a file that also runs git or reads this checkout -- same rule as .gitignore',
  },
]

/**
 * A quoted `git` in argv position: `spawnSync('git', ...)`, `execSync('git
 * status')`, `Bun.spawn(['git', ...])`, `` $`git ...` ``. Also catches an
 * absolute path to the binary (`'/usr/bin/git'`). Misses `spawnSync(GIT_BIN)`
 * -- under-matching there is the accepted cost of a 100-line script.
 */
const GIT_COMMAND = /(['"`])(?:[\w./-]*\/)?git(?:\1|[\s-])/

/**
 * A reach into THIS checkout rather than a scratch dir. The second banned shape
 * is reading the repo's own checked-in config back and asserting its contents;
 * a test of our generator's output has no reason to know where the repo is.
 */
const OWN_CHECKOUT = /import\.meta\.(?:dir|url)|__dirname|process\.cwd\(\)/

/** True when a file's assertions can reach past its own generated bytes. */
function testsGitOrTheCheckout(code: string): boolean {
  return GIT_COMMAND.test(code) || OWN_CHECKOUT.test(code)
}

/**
 * `source` with line and block comments blanked out, so a doc comment that
 * merely MENTIONS `.gitignore` is not a violation. Only code counts.
 */
function stripComments(source: string): string {
  return source.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/[^\n]*/g, '')
}

/** First code line in `code` containing `token`, or 0 if absent. */
function offendingLine(code: string, token: string): number {
  const lines = code.split('\n')
  for (let i = 0; i < lines.length; i++) {
    if (lines[i].includes(token)) return i + 1
  }
  return 0
}

/**
 * Findings for one test file. `code` is already comment-stripped; `file` is the
 * repo-relative path used in the report.
 */
function scanFile(file: string, code: string): LintFinding[] {
  const reachesOut = testsGitOrTheCheckout(code)
  return BANS.filter(ban => ban.unconditional || reachesOut)
    .map(ban => ({ ban, line: offendingLine(code, ban.token) }))
    .filter(hit => hit.line > 0)
    .map(hit => ({ file, line: hit.line, detail: `'${hit.ban.token}' -- ${hit.ban.why}` }))
}

function scanRoot(dir: string): LintFinding[] {
  const abs = join(ROOT, dir)
  return scanSourceFiles(abs, '**/*.{test,spec}.{ts,tsx}').flatMap(rel =>
    scanFile(join(dir, rel), stripComments(readFileSync(join(abs, rel), 'utf8'))),
  )
}

reportAndExit(
  TEST_ROOTS.flatMap(scanRoot),
  'no-config-tests: no test asserts VCS configuration -- OK',
  n => `no-config-tests: ${n} test(s) asserting version-control configuration`,
  'Git configuration for this repo does not get tests. Delete the assertion.\n' +
    'Testing a generator? Assert the BYTES it writes into a scratch dir -- never hand\n' +
    'them to git, and never read back the copy checked into this repo.',
)
